### ISSUE TITLE
Batch queries not working with queryId

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-smart-cache#102]
When making a batch request with a query and a queryId, as documented here: https://www.wpgraphql.com/docs/wpgraphql-vs-wp-rest-api/#batch-queries

The queryId is being rejected when sent alongside a query:

![CleanShot 2022-03-07 at 16 53 50](https://user-images.githubusercontent.com/1260765/157138131-c25d5f0d-826b-47f6-b445-96472c2d6f58.png)

However, I can make the same request as an individual query, and not get an error:

![CleanShot 2022-03-07 at 16 56 26](https://user-images.githubusercontent.com/1260765/157138365-f25cc4f3-7e6f-4daa-b1bb-2125aef55e39.png)

**Comment by markkelnar** [comment]
Are you trying to create a new saved query within a batch request?  Which for single requests can be accomplished with query string and queryId are provided on the request.

**Comment by markkelnar** [comment]
I think I found the issue and will work on a fix.

**Comment by jasonbahl** [comment]
This has been fixed. I've confirmed.

Querying via POST request for multiple queries using the `queryId` field returns the expected responses for both queries.

## Request

![CleanShot 2022-11-11 at 13 58 37](https://user-images.githubusercontent.com/1260765/201429707-77db3e31-d8da-452c-9a9c-36fd2810d5e9.png)

## Response 

![CleanShot 2022-11-11 at 13 59 01](https://user-images.githubusercontent.com/1260765/201429759-45c3fb12-0045-49f9-b81d-e57068ebd940.png)
