### ISSUE TITLE
Flywheel cache integration for wp-graphql

### ISSUE THREAD

**Issue by bhardie** [wp-graphql/wp-graphql-smart-cache#115]
To support requests over GET, we need to support invalidating cache in the stack when content changes on the backend. 

When content changes (post, customer post type, tag, category, etc), purge specific urls from Flywheel cache.

Example graphql query paths:
/graphql?queryId=query-posts&variables={ id: 1 }
/graphql?query={ posts {nodes { title } }
/custom?queryId=query-home-page

Create a [flywheel site](https://wpengine.atlassian.net/wiki/spaces/SE/pages/2391900474/How+to+sign+up+for+a+comped+account+on+Flywheel)

**Comment by markkelnar** [comment]
Worked with DanFitch to get info needed to use a fw logging function. Mostly there. Gonna do more testing. :+1:

**Comment by markkelnar** [comment]
We have refactored the graphql_purge action to listen for. Working to make that change in WPE farm. I think we close this until there is a flywheel need and make use of a similar purge mechism outside the smart-cache plugin, but in a vendor specific plugin.
