### ISSUE TITLE
Work on the documentation of how to transition to GET requests

### ISSUE THREAD

**Issue by markkelnar** [wp-graphql/wp-graphql-smart-cache#126]

**Comment by jasonbahl** [comment]
Closing this issue as we have documentation for using GET requests here: 

- https://github.com/wp-graphql/wp-graphql-smart-cache/blob/main/docs/network-cache.md#get-requests
- https://wpengine.com/builders/moving-get-post-requests-faust-js-1-0-wpgraphql/
