### ISSUE TITLE
Deploy to Composer

### ISSUE THREAD

**Issue by ditto-vlad** [wp-graphql/wp-graphql-smart-cache#168]
As a plugin user - I would like to use this plugin through composer or wordpress packagist.

I realize this plugin is still in beta. Playing with it for a while I noticed serious improvements in queries through caching. In order to streamline testing & integration, it would really help if I could install through composer.

Super cool plugin btw, appreciate the work you guys have been doing.
Keep up the good work

**Comment by jasonbahl** [comment]
ok, after more thought, I decided putting it on Composer now, even while technically beta, is a good move. WordPress.org will come a bit later. 

It's now on packagist.org here: https://packagist.org/packages/wp-graphql/wp-graphql-smart-cache

and the webhook is in place so as we push out releases, packagist will get the latest version
