### ISSUE TITLE
Disable debug extension

### ISSUE THREAD

**Issue by samyrooster** [wp-graphql/wp-graphql-smart-cache#169]
Is there any option/hook to disable the `debug` or `graphqlSmartCache` extensions in the response?

**Comment by jasonbahl** [comment]
@samyrooster the debug message should only be output if you're running WPGraphQL in Debug mode. If you disable debug mode, the debug messages should go away. 

To remove the `graphqlSmartCache` or `queryAnalyzer` output from the "extensions" response, you can use the following filter: 

```php
<?php
add_filter( 'graphql_request_results', function( $response ) {

	// remove the graphqlSmartCache response from the extensions
	if ( isset( $response->extensions['graphqlSmartCache'] ) ) {
		unset( $response->extensions['graphqlSmartCache'] );
	}

	// remove the queryAnalyzer response from the extensions
	if ( isset( $response->extensions['queryAnalyzer'] ) ) {
		unset( $response->extensions['queryAnalyzer'] );
	}

	return $response;

} , 99, 1 );
```
