### ISSUE TITLE
Is it possible to exclude specific queries & mutations from being cached?

### ISSUE THREAD

**Issue by alexkey89** [wp-graphql/wp-graphql-smart-cache#174]
It's crucial when doing login/logout in apollo etc that those won't get cached.

**Comment by jasonbahl** [comment]
@alexkey89 Currently this plugin doesn't cache Mutations. 

Additionally, this plugin should not be caching Authenticated requests. So, once you're logged in, if you're making Authenticated requests, they should all be cache misses and execute the resolvers in WordPress to get the response. 

If you're experiencing different behavior, open a new issue with steps to reproduce. 🙏🏻
