### ISSUE TITLE
I instead the plugin, but it have a Fatal error

### ISSUE THREAD

**Issue by jimcchi** [wp-graphql/wp-graphql-smart-cache#175]
the following is error message:

> Warning: /public_html/wp-content/plugins/wp-graphql-smart-cache-main/vendor/autoload.php): failed to open stream: No such file or directory in /public_html/wp-content/plugins/wp-graphql-smart-cache-main/wp-graphql-smart-cache.php on line 41
> 
> Fatal error: require(): Failed opening required '/public_html/wp-content/plugins/wp-graphql-smart-cache-main/vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear') in /public_html/wp-content/plugins/wp-graphql-smart-cache-main/wp-graphql-smart-cache.php on line 41

how can I fix it?

**Comment by stephanedemotte** [comment]
Same here @jimcchi is not `"wp-graphql/wp-graphql-smart-cache": "^0.3.1"` ?
