### ISSUE TITLE
wpgraphql version requirement issue

### ISSUE THREAD

**Issue by mdxprograms** [wp-graphql/wp-graphql-smart-cache#181]
PHP version: `7.4`
WP Version: `5.8.1`

We've installed the plugin, but are receiving an error alert in wp-admin with the following, requiring `v1.2.0+`
![Screen Shot 2022-11-14 at 1 48 14 PM](https://user-images.githubusercontent.com/1900735/201741579-3dee3cb2-b29c-4d49-a01d-e94479d0d25e.png)

But as you can see with below screen we are at `1.8`

![Screen Shot 2022-11-14 at 1 48 05 PM](https://user-images.githubusercontent.com/1900735/201741555-0b75ea30-bd74-4730-a01b-ec5578f575c6.png)

Any recommendations on what could be happening here?

**Comment by mdxprograms** [comment]
For what it's worth I'm also seeing this error stack trace in our server error messages:

```
Uncaught Error: Class 'WPGraphQL\SmartCache\Document' not found in /code/wp-content/plugins/wp-graphql-smart-cache/wp-graphql-smart-cache.php:115
Stack trace:
#0 /code/wp-includes/class-wp-hook.php(303): WPGraphQL\SmartCache\{closure}('')
#1 /code/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(Object(WPGraphQL\ACF\ACF), Array)
#2 /code/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#3 /code/wp-settings.php(578): do_action('init')
#4 /code/wp-config.php(185): require_once('/code/wp-settin...')
#5 /code/wp-load.php(50): require_once('/code/wp-config...')
#6 /code/wp-admin/admin.php(34): require_once('/code/wp-load.p...')
#7 /code/wp-admin/index.php(10): require_once('/code/wp-admin/...')
#8 {main}
thrown
```

**Comment by 2xSamurai** [comment]
+1 I'm also experiencing the same issue

**Comment by jasonbahl** [comment]
My guess is that you installed via composer? If you update to v0.3.2 do these errors go away?

If not, can ya'll provide clear steps to reproduce?

**Comment by jasonbahl** [comment]
Ok, so, one thing that I realize is wrong. . .the required version of WPGraphQL to work with WPGraphQL Smart Cache is `v1.12.0+`, not `1.2.0`. 

So if you're on v1.8.* of WPGraphQL, unfortunately WPGraphQL Smart Cache won't work with that version. 

If possible, I'd highly recommend updating core WPGraphQL to the latest version. 

If you're unable to for some reason, please open an issue describing what's holding you back from updating and we can see if we can help you get updated to the latest. 🙏🏻 

I'll open a PR to update the version requirement from `1.2.0` to `1.12.0`

**Comment by jasonbahl** [comment]
I believe this is resolved as of the latest release. 

If you are still experiencing this issue, please open a new issue and link to this one for reference. 

Thanks!
