### ISSUE TITLE
WPGraphQL (v1.12.0+) must be active for "wp-graphql-smart-cache" to work

### ISSUE THREAD

**Issue by jesperbogaard** [wp-graphql/wp-graphql-smart-cache#192]
Installed the plugin on WordPress version: 6.1.1 with WPGraphQL version 1.13.7 and WPGraphQL Smart Cache version: v1.0

After installation the message: "WPGraphQL (v1.12.0+) must be active for "wp-graphql-smart-cache" to work" appears in the WordPress backend and no options under GraphQL settings are visible related to Smart Cache.

**Comment by jasonbahl** [comment]
@jesperbogaard do you have any other plugins active? Did you install the plugins from WordPress.org or some other method (clone from Github, install from Composer?)

There was a conflict with a constant name if you also had WPGraphQL for ACF active that led to showing this message, but I _believe_ that was resolved.

Would love to know if you have other plugins (like WPGraphQL for ACF) active as well.

**Comment by jesperbogaard** [comment]
@jasonbahl I have installed the plugin from download/ clone from GitHub. Indeed we are using also WP GraphQL for ACF module. 

![Scherm­afbeelding 2023-01-04 om 08 09 48](https://user-images.githubusercontent.com/25544335/210502258-962bc8f8-0554-4e5c-8391-2e1cdc4ee5b1.png)

**Comment by jasonbahl** [comment]
@jesperbogaard if you install WPGraphQL Smart Cache from the WordPress.org repo do you see the error too?

**Comment by jesperbogaard** [comment]
Hi @jasonbahl now it is working, thanks.

**Comment by macojaune** [comment]
Hi @jasonbahl, I have the same issue when installing the module via composer. 
We use a dockerised wordpress, so each deployment I need to delete and reinstall via the wp store for it to work.
