### ISSUE TITLE
Purge Now button not purging WPE cache

### ISSUE THREAD

**Issue by markkelnar** [wp-graphql/wp-graphql-smart-cache#193]
In the WPGraphQL admin settings page, when the 'Purge Now' check box is selection under 'Cache' and the settings are saved, the 'wpgraphql_cache_purge_all' action is triggered. This action should trigger the WP Engine varnish network cache to invalidate all WP GraphQL data for the domain.

**Comment by jasonbahl** [comment]
closed by #194
