### ISSUE TITLE
Persisted query taxonomies are publicly visable, accesible and showing in sitemap

### ISSUE THREAD

**Issue by markkelnar** [wp-graphql/wp-graphql-smart-cache#198]
Saved aliases, ie persisted queries, are visible on the taxonomy url and also showing in sitemap.xml.

Example, http://example.com/graphql_query_alias/8d8f7365e9e86fa8e3313fcaf2131b801eafe9549de22373089cf27511858b39/

This should not be the behavior out of the box.

**Comment by jasonbahl** [comment]
closed by #200
