### ISSUE TITLE
"Something is wrong with the form data" is shown often for persisted queres

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-smart-cache#199]
**Problem:**

When using the GUI for "GraphQL Documents" post type, there's an admin error shown quite often:

To reproduce:

- with WPGraphQL Smart Cache active and the "Display saved query documents in admin editor" setting turned on
- visit the "GraphQL Documents > Add New" screen. 

See the following admin error:

![CleanShot 2023-02-27 at 09 17 02](https://user-images.githubusercontent.com/1260765/221619039-83be1f38-b9bc-4d22-becd-d7d7fe775d60.png)

The error is returned by the code here:

https://github.com/wp-graphql/wp-graphql-smart-cache/blob/ab47d08455af252e58fa27e354edf4cd7a7888ba/src/Admin/Editor.php#L104

Which determines the form is invalid because the (yet to be created POST) isn't valid. 

We should shore up the logic that returns this admin error to only return if/when there's actually an error.

**Comment by markkelnar** [comment]
closed by #237
