### ISSUE TITLE
Create Mutation Error: post_exists

### ISSUE THREAD

**Issue by ditto-vlad** [wp-graphql/wp-graphql-smart-cache#209]
This Error happens when performing a mutation. 

[wp-graphql-smart-cache](https://github.com/wp-graphql/wp-graphql-smart-cache) version: 1.0.3

![Screenshot 2023-04-24 at 18 40 41](https://user-images.githubusercontent.com/87081580/234074408-79eab51c-3752-43f6-9743-8d2afe35731f.png)

![Screenshot 2023-04-24 at 18 18 42](https://user-images.githubusercontent.com/87081580/234069882-fdc269cf-8d56-4a2e-8bc8-decee88d81d9.png)

https://developer.wordpress.org/reference/functions/post_exists/

-- Related: #196

**Comment by matthewtompkins** [comment]
+1 to this, and for me I'm seeing it on user-facing content at times. Tried to open a PR but I don't have access to create a branch. This solution should work, as I think the it's possible that Invalidation is trying to call this function from outside an admin context:

```
                // Check if post_exists() is available
		if ( ! function_exists( 'post_exists' ) ) {
			require_once ABSPATH . '/wp-admin/includes/post.php';
		}
		// Check if $post_id is valid: Make sure that $post_id is a valid post ID.
		if ( ! post_exists( $post_id ) ) {
			return;
		}
```

Added to line 561 of /wpgraphql-smart-cache/src/Cache/Invalidation.php

**Comment by jasonbahl** [comment]
fix coming this morning. so sorry! 🤦🏻‍♂️

**Comment by jasonbahl** [comment]
@matthewtompkins in the future you can fork and open a PR from your fork.

**Comment by matthewtompkins** [comment]
@jasonbahl Cheers, thank you for the quick response!
