### ISSUE TITLE
Validation for publishing a GraphQL Document

### ISSUE THREAD

**Issue by jasonbahl** [wp-graphql/wp-graphql-smart-cache#243]
Currently GraphQL Documents can be published without any "required" information, such as a GraphQL Document or query alias. 

We should add validation that prevents a document from transitioning to the "publish" state if it doesn't have a valid graphql document. 

Since the Query Aliases are generated on save, perhaps we might only need a valid document, but without both the queries shouldn't be in a published state.

**Comment by jasonbahl** [comment]
@markkelnar good job thinking through the various state transitions. 

This all seems to line up with what I have in mind. 

one thing I'm not fully sure I follow is:

> if form errors, query string in editor reverts to last working version or blank. change to draft status to be able to save invalid query string

Can you elaborate what you mean here? If the user is modifying an already published document, why would we change it to draft?

**Comment by markkelnar** [comment]
We shouldn't save the invalid/broken graphql query.

When the user clicks save, we don't have a way to persist that invalid/broken query in the editor box without saving it to the WP post, therefore losing the previous "working" query.  One flow would be to keep the previous working query string, not including the edits being made. Leave it as published.  And just show an error message at the top of the editor screen.  But the query that was being edited is "lost".  The user doesn't see the query anywhere, has no good information about what was broken and can not see what the query was when it was saved.  They would be confused as to what was wrong and how to continue editing the query, even if it were broken.  This flow would give them a change to continue editing the "broken" query in a 'non-published' status until they get it correct.  Once it is valid, it can be 'published'.

Another thought is that queries, once "working and published" can not be edited.  But instead must be cloned or saved as a new different query.  I think we have that ticket/issue somewhere.  Maybe that would solve this scenario.

Another thought, we open the graphiql editor to "Edit queries", utilized the functionality there to create/edit queries.  And include a "save" in graphiql ide.

**Comment by jasonbahl** [comment]
> Another thought is that queries, once "working and published" can not be edited. But instead must be cloned or saved as a new different query. I think we have that ticket/issue somewhere. Maybe that would solve this scenario.

That's what I was thinking. 

If the document string (the post_content) is modified in a valid way, we would save it as a new post. (I think there probably would need to be a dialog or something where the user could confirm they want to save a new query. Something like: "Would you like to save this as a new query or dismiss the changes?" or something to that tune. This could come later, if needed, but would be a good UX addition, I think.

If the document string (post_content) is modified in a non-valid way, we should keep the previously valid document string, but display an error about why the modification did not save.
