### ISSUE TITLE
Do not allow query strings to be edited in Editor for published queries

### ISSUE THREAD

**Issue by markkelnar** [wp-graphql/wp-graphql-smart-cache#254]
When a saved persisted query has been published, changing the query string changes the autmoatically calculated alias hash string.  This removes the existing/old alias hash making it unusable and potentially breaking any client apps using that query.

This change will prevent the WP admin editor from allowing edits to an already published saved query string.

**Comment by josephfusco** [comment]
Closing in favor of https://github.com/wp-graphql/wp-graphql-smart-cache/issues/259 as this was marked duplicate.
