### ISSUE TITLE
Document WP Engine's Lower Cache Limit

### ISSUE THREAD

**Issue by rodrigo-arias** [wp-graphql/wp-graphql-smart-cache#281]
The documentation states that [setting a custom max-age per document](https://github.com/wp-graphql/wp-graphql-smart-cache/blob/main/docs/persisted-queries.md#custom-max-age--expiration-per-query) is possible, which is helpful for 'Settings' or other queries that may not be invalidated properly. However, it appears that WP Engine has certain limitations.

[WP Engine support page on Cache Control Headers](https://wpengine.com/support/cache-control-headers-wp-engine/)

- The X-Cacheable header will be set to `YES:[MAX-AGE].000` for any value equal to or greater than 600. For values less than 600, it will be set to `SHORT`.
- The Cache-Control header will include `max-age=[MAX-AGE], must-revalidate`, and the MAX-AGE will be overwritten to 600 for any value lower than that.

While the WP Engine rule seems restrictive and prevents us to not to caching certain documents, mentioning it in the documentation could be beneficial as it might take time to discover and understand this behavior.

**Comment by theodesp** [comment]
@rodrigo-arias I think that the MU plugin for cache settings override any Cache control headers that you may set. So can you change those Cache Control headers in the Admin?

https://wpengine.com/support/cache/#WordPress_Admin

**Comment by rodrigo-arias** [comment]
@theodesp Thanks for bringing that up. I'm not sure whether the MU plugin is enforcing the `Cache-Control` headers or if it's coming from NGINX, probably the second. From the admin side, the cache duration can only be adjusted per post type or REST API namespace—and even then, there's a hard minimum of 10 minutes.

I've raised this with WP Engine. I understand the limit is in place for performance reasons, but I think it's necessary to have a way for advanced users to override it—perhaps via a custom header like `X-Bypass-Cache: true` or something similar.
