### ISSUE TITLE
Querying graphqlDocument returns no results

### ISSUE THREAD

**Issue by archoda** [wp-graphql/wp-graphql-smart-cache#285]
Cannot query the current existing documents with any of the existing registered types. Even if only base plugins are installed.

```
graphqlDocument
graphqlDocumentBy
graphqlDocuments
```
![Screenshot 2024-07-01 at 9 22 07 PM](https://github.com/wp-graphql/wp-graphql-smart-cache/assets/4642545/9321d10b-0790-4e03-ac8c-bde02e8accb7)
![Screenshot 2024-07-01 at 9 27 51 PM](https://github.com/wp-graphql/wp-graphql-smart-cache/assets/4642545/ad5b1492-fccc-4e67-b2f4-b3775f3e0889)
![Screenshot-2024-07-01-at-9 21 28 PM](https://github.com/wp-graphql/wp-graphql-smart-cache/assets/4642545/924833db-4620-46fe-9aa8-bd9f4af131d2)

**Comment by josephfusco** [comment]
Hey @archoda, it appear that you are attempting to query the documents as a public user however [GraphQL documents are not public](https://github.com/wp-graphql/wp-graphql-smart-cache/blob/343cbdb11a8976afa65454abd3d7a8402355f108/src/Document.php#L50-L51).

You can either execute queries as an authenticated user, or update/filter the post type to be public based on your needs.

You could use the [register_post_type_args](https://developer.wordpress.org/reference/hooks/register_post_type_args/) filter to make the post type public.

Or you can [filter the model in GraphQL](https://github.com/wp-graphql/wp-graphql/blob/develop/src/Model/Model.php#L254) to allow a non-public post type to be publicly queryable in GraphQL.

**Comment by josephfusco** [comment]
I'm going to close this as I believe this is working as expected.
I hope the links provided above are helpful, and please open up a new issue if you run into any issues. 🙌🏼
